name: Deploy
# on: [push,workflow_dispatch]

# Triggered only if the changes in main branch - FIltering


on:
    push:
        branches:
          - main
        # paths-ignore:

        #   # When anything changes in the following file then no need to re-deployment
        #     - '.github/workflows/*'
        #     - README.md
    workflow_dispatch:
      
        




# Method -2  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# on:
#     - push
#     - workflow_dispatch
# - push
#     - workflow_dispatch    - Represeting list of item
jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Get Code"
              uses: actions/checkout@v4
            #   run: |
            #      echo "Hello, world!"
            #      echo "Bye Bye"
            - name: "Intall Node 20"
              uses: actions/setup-node@v4
              with: 
                node-version: 20

            - name: cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
               
            - name: print node version
              run: node -v
            - name: Install dependencies
              run: npm ci
            - name: Run Tests
              run: npm run test
   

    build:
        needs: test
        runs-on: ubuntu-latest

        steps:
          - name: "Get Code"
            uses: actions/checkout@v4
       
          - name: "Intall Node 20"
            uses: actions/setup-node@v4
            with: 
              node-version: 20
          - name: cache dependencies
            uses: actions/cache@v4
            with:
              path: ~/.npm
              key: ${{ runner.os}}-node-${{ hashFiles('**/package-lock.json') }}
           
          - name: Install dependencies
            run: npm ci

          - name: Build Project
            run: npm run build"
          - name: Upload Dist Artifact
            uses: actions/upload-artifact@v4

            with:
                name: dist-files
                path: dist

        

    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:

          - name: Upload Dist Artifact
            uses: actions/download-artifact@v4

            with:
                name: dist-files
                path: dist
        
          - name: Deploy
            run: echo "Deploy successfully"


    
